### ISSUE TITLE
v10

### ISSUE THREAD

**Issue by brunocalado** [YourFavouriteOreo/VTT-Chat-GIFs#12] opened 2023-01-17 13:24 UTC
Please make it work for v10

**Comment by YourFavouriteOreo** [comment] 2023-01-17 13:46
Could you please provide me with more information on what's happening?

**Comment by brunocalado** [comment] 2023-01-17 13:53
update error
![image](https://user-images.githubusercontent.com/4999783/212916084-08451349-c99b-48c3-a7b5-576b0aeb953d.png)

swade better rolls mode is blocked
![image](https://user-images.githubusercontent.com/4999783/212916547-8906449f-d40d-481c-a128-5262fcfe11f1.png)

**Comment by B14d3r11** [comment] 2023-01-19 07:17
> update error ![image](https://user-images.githubusercontent.com/4999783/212916084-08451349-c99b-48c3-a7b5-576b0aeb953d.png)
> 
> swade better rolls mode is blocked ![image](https://user-images.githubusercontent.com/4999783/212916547-8906449f-d40d-481c-a128-5262fcfe11f1.png)

I am also having this issue where the Search for a Gif is constantly open and floating middle of my chat

**Comment by YourFavouriteOreo** [comment] 2023-01-19 07:18
ill look into it

**Comment by MotoMoto1234** [comment] 2023-01-21 02:20
The giphy window does not close when you are done with it, I feel like the GIF button should toggle the window?  but theres no way to close it so it just sits there blocking chat.  Also now the module.json doesn't have a manifest link anymore so we can't install/reinstall it.

**Comment by DekuScrubs** [comment] 2023-02-02 17:39
I'm having the same issue with the Gif Search bar constantly up and blocking the chat

**Comment by Sanders47** [comment] 2023-04-14 05:44
Any updates on this?

**Comment by YourFavouriteOreo** [comment] 2023-04-26 12:34
I am looking into this bug but having difficult replicating it. Can someone give me a full list of modules used to cause the bug and the foundry version and world?

**Comment by brunocalado** [comment] 2023-04-26 13:34
> I am looking into this bug but having difficult replicating it. Can someone give me a full list of modules used to cause the bug and the foundry version and world?

![image](https://user-images.githubusercontent.com/4999783/234591970-aab97a1f-5378-4787-9f64-5a593a1cc602.png)

```
### Active Modules
3D Canvas Mapmaking Pack v7.1.2
3D Canvas Token Collection v0.8.6
Alternative Pause Icon v1.0.3
Always Chat v1.0.2 [Bugs URL](https://github.com/mouse0270/always-chat/issues)
A/V Quality of Life v1.1.1 [Bugs URL](https://github.com/patrickporto/avqol/issues)
Babele v2.4.0
Brazilian Portuguese [SWADE] v2.0.0
Bar Brawl v1.8.0 [Bugs URL](https://gitlab.com/woodentavern/foundryvtt-bar-brawl/-/issues)
Challenge Tracker v2.2
Chat GIFs v1.0.4
Chat Images v3.2
Chat Portrait v0.8.46 [Bugs URL](https://github.com/p4535992/foundryvtt-chat-portrait/issues)
Cleaner sheet title bar v1.5.1
Compendium Folders v2.5.7
Custom CSS v2.2.1 [Bugs URL](https://github.com/cswendrowski/FoundryVTT-Custom-CSS/issues)
DFreds Droppables v2.1.0 [Bugs URL](https://github.com/DFreds/dfreds-droppables/issues)
Dice So Nice! v4.6.7 [Bugs URL](https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/issues)
More Bennies - SWADE v0.2.2
Omniscient Die v1.5
Dice Tray v1.5.3
Drag Anything to Hotbar v1.1.0
Easy Polls v1.3.3 [Bugs URL](https://github.com/mclemente/foundryvtt-easy-polls/issues)
Filepicker Improvements v1.2.5 [Bugs URL](https://github.com/manuel-hegner/foundry-filepicker-favorites/issues)
Find the culprit v1.4.6 [Bugs URL](https://github.com/Moerill/fvtt-find-the-culprit/issues)
Forien's Quest Log v0.7.11 [Bugs URL](https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues)
FoundryVTT Arms Reach v2.2.12 [Bugs URL](https://github.com/p4535992/foundryvtt-arms-reach/issues)
FXMaster v3.6.0 [Bugs URL](https://github.com/ghost-fvtt/fxmaster/issues)
Hourglass v1.5.1
Hover Distance v2.1
Illandril's Chat Enhancements v2.1.4 [Bugs URL](https://github.com/illandril/FoundryVTT-chat-enhancements/issues)
Illandril's Token HUD scaler v2.2.1 [Bugs URL](https://github.com/illandril/FoundryVTT-token-hud-scale/issues)
Image Hover v3.0.0 [Bugs URL](https://github.com/Eriku33/Foundry-VTT-Image-Hover/issues)
Item Piles v2.6.8 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-ItemPiles/issues)
JB2A - Patreon Complete Collection v0.5.6
Layer Hotkeys v2.4.1
CodeMirror v5.58.3-fvtt5
Color Picker v1.2
Library: Active effect manager v0.2.4 [Bugs URL](https://github.com/p4535992/foundryvtt-active-effect-manager-lib/issues)
libWrapper v1.12.12.0 [Bugs URL](https://github.com/ruipin/fvtt-lib-wrapper/issues)
Math.js v7.5.1-fvtt2
Settings Extender v1.2.1
socketlib v1.0.12 [Bugs URL](https://github.com/manuelVo/foundryvtt-socketlib/issues)
SortableJS v1.14.0-fvtt1
LiveKit AVClient v0.5.21 [Bugs URL](https://github.com/bekriebel/fvtt-module-avclient-livekit/issues)
Macro Manager v0.2.5
Macro Wheel v1.3
Melvin's Mechanical Masterworks v2.4.0
Module Management+ v2.1.6 [Bugs URL](https://github.com/mouse0270/module-credits/issues)
Monk's Active Tile Triggers v10.15 [Bugs URL](https://github.com/ironmonk88/monks-active-tiles/issues)
Monk's Combat Marker v10.1 [Bugs URL](https://github.com/ironmonk88/monks-combat-marker/issues)
Monk's Little Details v10.8 [Bugs URL](https://github.com/ironmonk88/monks-little-details/issues)
Monk's Sound Enhancements v10.02 [Bugs URL](https://github.com/ironmonk88/monks-sound-enhancements/issues)
My Assets v1.0.0
Narrator Tools v0.78
Ownership Viewer v0.10.0 [Bugs URL](https://github.com/Malekal4699/fvtt-module-permission-viewer/issues)
PDF Pager v0.40.0
Playerlist don't cover Controls Bar v1.3.0
Portuguese (BR) Core v2.0.0
Potato Or Not v0.6.0 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-PotatoOrNot/issues)
Precious Stones Art Pack v0.0.4
Quickdraw v0.4
Quick Insert - Search Widget v2.8.0 [Bugs URL](https://gitlab.com/fvtt-modules-lab/quick-insert/-/issues)
✋ Raise My Hand v1.4.2
Roll Table from Sidebar and Journal v1.3.1
Savaged.us Importer v3.8.3 [Bugs URL](https://gitlab.com/kristianserrano/savagedus-importer/-/issues)
Savage Pathfinder v2.0.1 [Bugs URL](https://support.sigil-services.com)
Savage Pathfinder Bestiary v2.0.0
Savage Pathfinder (PT-BR) v1.1.1
Savage Worlds Edição Aventura Regras Básicas v2.1.1
Scenery - Background Image Variation Manager v1.1.2 [Bugs URL](https://github.com/marcstraube/foundryvtt-scenery/issues)
Sequencer v3.0.1 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Sequencer/issues)
Automated Animations v4.2.47
Automated Evocations - Companion Manager v1.8.7
Share Media v0.0.39
Simple Calendar v2.1.80 [Bugs URL](https://github.com/vigoren/foundryvtt-simple-calendar/issues)
SmallTime v1.16.3 [Bugs URL](https://github.com/unsoluble/smalltime/issues)
Smart Target v0.9.8 [Bugs URL](https://github.com/theripper93/Smart-Target/issues)
Split-Join Journal v1.0.0 [Bugs URL](https://github.com/toastygm/split-join-journal/issues)
Stairways (Teleporter) v0.9.1 [Bugs URL](https://gitlab.com/SWW13/foundryvtt-stairways/issues)
SWADE Core v1.0.0
SWADE Fantasy Currencies v0.5.2 [Bugs URL](https://github.com/ddbrown30/sfc/issues)
SWADE Stat Block Importer v0.2.1 [Bugs URL](https://github.com/arnonram/swade-npc-importer/issues)
SWADE Ultimate Condition Changer v0.2.7
Better Rolls 2 for Savage Worlds v3.23
Tagger v1.4.4 [Bugs URL](https://github.com/fantasycalendar/FoundryVTT-Tagger/issues)
Tile Scroll v1.9
Token Attacher v4.5.12
Mount Up! v3.4.3 [Bugs URL](https://github.com/p4535992/foundryvtt-mountup/issues)
Tokenizer v4.0.3
Token Magic FX v0.6.2
Token Tooltip Alt v3.1.5
Token Variant Art v4.37.0 [Bugs URL](https://github.com/Aedif/TokenVariants/issues)
Token Z v0.8.1
Torch v2.6.0
Wall Height v4.9.6
Levels v3.8.1
3D Canvas v4.23
Warp Gate v1.16.2
Savage Pathfinder - Enhanced v0.5.2
☯ Wheel Of Destiny v0.1.7
```

**Comment by YourFavouriteOreo** [comment] 2023-04-26 13:42
What foundry version?

**Comment by brunocalado** [comment] 2023-04-26 13:43
> What foundry version?

![image](https://user-images.githubusercontent.com/4999783/234594499-0173a392-7b5e-4e57-b538-4cae0b1e3dab.png)

**Comment by MotoMoto1234** [comment] 2023-05-02 07:43
this bug shows up with just chat gif enabled fyi.  But you have to have the version that is no longer downloadable, it seems its been pulled.

**Comment by YourFavouriteOreo** [comment] 2023-05-02 07:56
I did have to do a pull at some point for a bug . The issue is those who are stuck in the older version don't get an alert that there is an update because I messed up the json long ago, might be fixable with an update on the admin panel but I am not exactly sure where things are going wrong. It can usually be fixed with a re-install

**Comment by brunocalado** [comment] 2023-05-02 16:50
> I did have to do a pull at some point for a bug . The issue is those who are stuck in the older version don't get an alert that there is an update because I messed up the json long ago, might be fixable with an update on the admin panel but I am not exactly sure where things are going wrong. It can usually be fixed with a re-install

I deleted and installed again. This is a problem with Better Rolls 2 module..

https://user-images.githubusercontent.com/4999783/235732111-2b8e48dc-1c6b-4d02-b97c-17c8be63cf5d.mp4

**Comment by MotoMoto1234** [comment] 2023-05-08 17:52
> I did have to do a pull at some point for a bug . The issue is those who are stuck in the older version don't get an alert that there is an update because I messed up the json long ago, might be fixable with an update on the admin panel but I am not exactly sure where things are going wrong. It can usually be fixed with a re-install

The combat tracker bug is more breaking than this cause I shared a custom css module entry to fix the location and how it behaves.  Its the strange interaction this module has with hidden creatures in the combat tracker that makes it hard to use the module with any system that uses combat.

**Comment by YourFavouriteOreo** [comment] 2023-05-09 04:56
Alright, ill focus on the fix for the combat tracker then switch to the forever visiblity

**Comment by Asinphi** [comment] 2023-08-15 01:58
The issues mentioned here should be fixed, and compatibility with v11 is implemented. It probably works fine with v10 (haven't tested), but either way, v10 probably won't be getting more support from me.

**Closed as completed by Asinphi** 2023-08-15 01:58 UTC
